/**
 * Core type definitions for the Tag Aliases plugin.
 */

/** An alias group: one primary tag mapped to multiple aliases. */
export interface AliasGroup {
    /** Unique identifier for this group. */
    id: string;
    /** The primary (canonical) tag, including '#' prefix, e.g. "#javascript". */
    primaryTag: string;
    /** List of alias tags, each including '#' prefix, e.g. ["#js", "#JS"]. */
    aliases: string[];
    /** Optional human-readable description for this alias group. */
    description?: string;
}

/** Plugin settings persisted via loadData/saveData. */
export interface TagAliasSettings {
    /** All alias groups managed by the user. */
    aliasGroups: AliasGroup[];
    /**
     * Whether to auto-replace alias tags with primary tags
     * when the user bypasses the suggestion popup.
     * Defaults to true.
     */
    autoReplace: boolean;
}

/** A single suggestion item shown in the editor tag suggest popup. */
export interface TagSuggestionItem {
    /** The tag text to insert into the editor (always the primary tag). */
    insertText: string;
    /** The tag name displayed in the suggestion list. */
    displayText: string;
    /** How this suggestion was matched: via primary tag name, alias, or neither. */
    matchSource: 'primary' | 'alias' | 'none';
    /** If matched via alias, the alias string that triggered the match. */
    matchedAlias?: string;
    /** The alias group this tag belongs to, if any. */
    group?: AliasGroup;
    /** Number of times this tag appears in the vault. */
    count?: number;
}

/** A planned replacement for batch migration. */
export interface MigrationChange {
    /** The file path to modify. */
    filePath: string;
    /** Individual replacements within this file. */
    replacements: MigrationReplacement[];
}

/** A single tag replacement within a file. */
export interface MigrationReplacement {
    /** The original alias tag to replace. */
    from: string;
    /** The target primary tag. */
    to: string;
    /** Where the tag is located: inline in content or in YAML frontmatter. */
    location: 'inline' | 'frontmatter';
}

/** The full migration plan generated by scanning the vault. */
export interface MigrationPlan {
    /** List of files with planned changes. */
    changes: MigrationChange[];
    /** Total number of tag replacements across all files. */
    totalReplacements: number;
}
